# Generated by Django 3.2.7 on 2021-09-19 16:13

import apps.utils.slug_generation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.SlugField(default=apps.utils.slug_generation.generate_slug, max_length=8, unique=True),
        ),
    ]
